apiVersion: v1
kind: ConfigMap
metadata:
  name: datastore-fe-cm
  namespace: {{.Values.StudentStoreFrontend.studentFeCm.namespace}}
data:
  backendEndpoint: {{.Values.StudentStoreFrontend.studentFeCm.backendEndpoint}}