apiVersion: v2
kind: Service
metadata:
  name: datastore-frontend-lb
spec:
  type: LoadBalancer
  selector:
    type: frontend
  ports:
    - port: 80
      targetPort: 8081
~                                                                                                                                                                      
~                                                                                                                                                                      
~                                                                                                                                                                      
~                                                                                                                                                                      
~                                                                                                                                                                      
~                                                                                                                                                                      
~                                                                                                                                                                      
~                           