apiVersion: v1
kind: ConfigMap
namespace: {{.Values.StudentStoreFrontend.studentFeCm.namespace}}
metadata:
  name: datastore-fe-cm
data:
  backendEndpoint: {{.Values.StudentStoreFrontend.studentFeCm.backendEndpoint}}