apiVersion: apps/v1
kind: Deployment
namespace: {{.Values.StudentStoreFrontend.StudentDeploy.namespace}}
{{- with .Values.StudentStoreFrontend.StudentDeploy}}
metadata:
  name: datastore-frontend
  labels:
    type: frontend
spec:
  template:
    metadata:
      name: datastore-frontend
      labels:
        type: frontend
    spec:
      containers:
        - name: mywebapp
          image: 8072388539/datastore-frontend:{{.imgTag}}
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: datastore-fe-cm
                  key: backendEndpoint
          resources: {{- toYaml .containerResources | nindent 12}}
           
          livenessProbe: {{- toYaml .livenessProbe | nindent 12}}
            
          readinessProbe: {{- toYaml .readinessProbe | nindent 12}}
            
          startupProbe: {{- toYaml .startupProbe | nindent 12}}
  replicas: {{.replicaCount}}
  selector:
    matchLabels:
      type: frontend

---

apiVersion: v1
kind: Service
namespace: {{.Values.StudentStoreFrontend.studentSvc.namespace}}
metadata:
  name: datastore-frontend-svc
spec:
  ports:
    - port: {{.Values.StudentStoreFrontend.studentSvc.svcPort}}
      targetPort: 8080
  selector:
    type: frontend

{{- end }}