{{- with .Values.StudentStoreBackend.StudentDeploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore-backend
  namespace: {{ .namespace }}
  labels:
    type: backend
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      name: datastore-backend
      labels:
        type: backend
    spec:
      containers:
        - name: datastore-backend
          image: 8072388539/datastore:{{ .image }}
          ports:
            - containerPort: 8084
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: datastore-be-cm
                  key: mysqlHost
            - name: MYSQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: datastore-be-cm
                  key: mysqlUname
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datastore-be-secret
                  key: mysqlPassword
          resources:
{{ toYaml .resources | indent 12 }}
          livenessProbe:
{{ toYaml .livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .readinessProbe | indent 12 }}
          startupProbe:
{{ toYaml .startupProbe | indent 12 }}
{{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: datastore-backend-svc
  namespace: {{ .Values.StudentStoreBackend.StudentSvc.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.StudentStoreBackend.StudentSvc.svcPort }}
      targetPort: 8084
  selector:
    type: backend